In [1]:
%%capture
!pip install torch transformers datasets pandas scikit-learn

# Load training data

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from transformers import BertTokenizer, BertForSequenceClassification, AdamW, get_scheduler, DataCollatorWithPadding # Import BertForSequenceClassification


# load training data:
data = pd.read_csv('/kaggle/input/incidents-train-dataset/incidents_train.csv', index_col=0)
train_df, dev_df = train_test_split(data, test_size=0.2, random_state=2024)

train_df.sample()

,year,month,day,country,title,text,hazard-category,product-category,hazard,product
ind,,,,,,,,,,
3738,2019,9,20,ca,Parador Plus brand Bouillon Chicken Concentrat...,Notice This archive of previously issued food ...,biological,"soups, broths, sauces and condiments",yeasts,chicken broth

In [2]:
data.title.str.split().apply(len).describe()

count    5082.000000
mean       13.282369
std         5.229355
min         1.000000
25%        10.000000
50%        13.000000
75%        16.000000
max        44.000000
Name: title, dtype: float64

Train and Evaluate BERT

In [3]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification, AdamW, get_scheduler, DataCollatorWithPadding

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

def tokenize_function(examples):
    return tokenizer(examples['title'], padding=True, truncation=True)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

Data preprocessing function:

In [4]:
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import DataLoader
from datasets import Dataset

def prepare_data(label):
    # encode labels:
    label_encoder = LabelEncoder()
    label_encoder.fit(data[label])

    train_df['label'] = label_encoder.transform(train_df[label])
    dev_df['label'] = label_encoder.transform(dev_df[label])

    # Convert DataFrame to Hugging Face Dataset
    train_dataset = Dataset.from_pandas(train_df)
    dev_dataset = Dataset.from_pandas(dev_df)

    # Apply the tokenizer to the dataset
    train_dataset = train_dataset.map(tokenize_function, batched=True)
    dev_dataset = dev_dataset.map(tokenize_function, batched=True)

    # Create DataCollator to handle padding
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer, padding=True, max_length=16)

    # Convert dataset to PyTorch format
    train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])
    dev_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])

    # Create DataLoader objects
    return (
        DataLoader(train_dataset, shuffle=True, batch_size=8, collate_fn=data_collator),
        DataLoader(dev_dataset, batch_size=8, collate_fn=data_collator),
        label_encoder
    )

Evaluation function:

In [5]:
from sklearn.metrics import f1_score

def compute_score(hazards_true, products_true, hazards_pred, products_pred):
  # compute f1 for hazards:
  f1_hazards = f1_score(
    hazards_true,
    hazards_pred,
    average='macro'
  )

  # compute f1 for products:
  f1_products = f1_score(
    products_true[hazards_pred == hazards_true],
    products_pred[hazards_pred == hazards_true],
    average='macro'
  )

  return (f1_hazards + f1_products) / 2.

#Sub-Task 1:

### Label: `Hazard Category`

* Data preprocessing

In [6]:
label = 'hazard-category'

# Create DataLoader objects
train_dataloader, dev_dataloader, le_hazard_category = prepare_data(label)

Map:   0%|          | 0/4065 [00:00<?, ? examples/s]

Map:   0%|          | 0/1017 [00:00<?, ? examples/s]

* Choose your model

In [7]:
model_hazard_category = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(data[label].unique()))
model_hazard_category.to('cuda')

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=10, bias=True)
)

* Train it

In [8]:
from tqdm.auto import tqdm

optimizer = AdamW(model_hazard_category.parameters(), lr=5e-5)

num_epochs = 3
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    name="linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)

model_hazard_category.train()

progress_bar = tqdm(range(num_training_steps))

for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_hazard_category(**batch)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

  0%|          | 0/1527 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2888: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

* Assess it

In [9]:
from sklearn.metrics import classification_report

model_hazard_category.eval()
total_predictions = []
with torch.no_grad():
    for batch in dev_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_hazard_category(**batch)
        predictions = torch.argmax(outputs.logits, dim=-1)
        total_predictions.extend([p.item() for p in predictions])

predicted_labels = le_hazard_category.inverse_transform(total_predictions)
gold_labels = le_hazard_category.inverse_transform(dev_df.label.values)
print(classification_report(gold_labels, predicted_labels, zero_division=0))

dev_df['predictions-hazard-category'] = predicted_labels

                                precision    recall  f1-score   support

                     allergens       0.87      0.90      0.88       363
                    biological       0.89      0.94      0.91       349
                      chemical       0.75      0.71      0.73        65
food additives and flavourings       0.60      0.75      0.67         4
                foreign bodies       0.81      0.87      0.84       105
                         fraud       0.75      0.64      0.69        78
          organoleptic aspects       0.67      0.18      0.29        11
                  other hazard       0.55      0.38      0.45        29
              packaging defect       0.83      0.38      0.53        13

                      accuracy                           0.85      1017
                     macro avg       0.75      0.64      0.66      1017
                  weighted avg       0.84      0.85      0.84      1017

In [10]:
print(predicted_labels)

['foreign bodies' 'chemical' 'other hazard' ... 'chemical' 'biological'
 'biological']

In [11]:
model_hazard_category.save_pretrained("bert_hazard_category")
np.save("bert_hazard_category/label_encoder.npy", le_hazard_category.classes_)

### Label: `Product Category`

In [12]:
label = 'product-category'

# Create DataLoader objects
train_dataloader, dev_dataloader, le_product_category = prepare_data(label)

Map:   0%|          | 0/4065 [00:00<?, ? examples/s]

Map:   0%|          | 0/1017 [00:00<?, ? examples/s]

* Train

In [13]:
model_product_category = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(data[label].unique()))
model_product_category.to('cuda')  # Move model to GPU if available

optimizer = AdamW(model_product_category.parameters(), lr=5e-5)
num_epochs = 3
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    name="linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)

model_product_category.train()
progress_bar = tqdm(range(num_training_steps))
for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_product_category(**batch)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

  0%|          | 0/1527 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2888: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

* Test

In [14]:
model_product_category.eval()
total_predictions = []
with torch.no_grad():
    for batch in dev_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_product_category(**batch)
        predictions = torch.argmax(outputs.logits, dim=-1)
        total_predictions.extend([p.item() for p in predictions])

predicted_labels = le_product_category.inverse_transform(total_predictions)
gold_labels = le_product_category.inverse_transform(dev_df.label.values)
print(classification_report(gold_labels, predicted_labels, zero_division=0))

dev_df['predictions-product-category'] = predicted_labels

                                                   precision    recall  f1-score   support

                              alcoholic beverages       0.77      0.83      0.80        12
                      cereals and bakery products       0.75      0.77      0.76       123
     cocoa and cocoa preparations, coffee and tea       0.71      0.81      0.76        42
                                    confectionery       0.50      0.44      0.47        32
dietetic foods, food supplements, fortified foods       0.68      0.62      0.65        24
                                    fats and oils       1.00      1.00      1.00         3
                   food additives and flavourings       0.00      0.00      0.00         2
                           food contact materials       0.00      0.00      0.00         1
                            fruits and vegetables       0.78      0.80      0.79       109
                                 herbs and spices       0.69      0.46      0.55        24
                                ices and desserts       0.90      0.90      0.90        50
                     meat, egg and dairy products       0.88      0.92      0.90       286
                          non-alcoholic beverages       0.87      0.84      0.86        32
                     nuts, nut products and seeds       0.79      0.81      0.80        62
                       other food product / mixed       0.00      0.00      0.00         6
                                         pet feed       0.00      0.00      0.00         6
                       prepared dishes and snacks       0.47      0.51      0.49        95
                                          seafood       0.87      0.80      0.84        51
             soups, broths, sauces and condiments       0.66      0.72      0.69        54
                                sugars and syrups       0.00      0.00      0.00         3

                                         accuracy                           0.77      1017
                                        macro avg       0.57      0.56      0.56      1017
                                     weighted avg       0.75      0.77      0.76      1017

In [15]:
model_product_category.save_pretrained("bert_product_category")
np.save("bert_product_category/label_encoder.npy", le_product_category.classes_)

## Evaluate Sub-Task

In [16]:
score = compute_score(
    dev_df['hazard-category'], dev_df['product-category'],
    dev_df['predictions-hazard-category'], dev_df['predictions-product-category']
)
print(f"Score Sub-Task 1: {score:.3f}")

Score Sub-Task 1: 0.610

## Sub-Task 2:

### Label: `Hazard`

In [17]:
label = 'hazard'

# Create DataLoader objects
train_dataloader, dev_dataloader, le_hazard = prepare_data(label)

Map:   0%|          | 0/4065 [00:00<?, ? examples/s]

Map:   0%|          | 0/1017 [00:00<?, ? examples/s]

In [18]:
model_hazard = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(data[label].unique()))
model_hazard.to('cuda')  # Move model to GPU if available

optimizer = AdamW(model_hazard.parameters(), lr=5e-5)

num_epochs = 3
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    name="linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)

model_hazard.train()

progress_bar = tqdm(range(num_training_steps))

for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_hazard(**batch)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

  0%|          | 0/1527 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2888: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [19]:
model_hazard.eval()
total_predictions = []
with torch.no_grad():
    for batch in dev_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_hazard(**batch)
        predictions = torch.argmax(outputs.logits, dim=-1)
        total_predictions.extend([p.item() for p in predictions])

predicted_labels = le_hazard.inverse_transform(total_predictions)
gold_labels = le_hazard.inverse_transform(dev_df.label.values)
print(classification_report(gold_labels, predicted_labels, zero_division=0))

dev_df['predictions-hazard'] = predicted_labels

                                                   precision    recall  f1-score   support

                                        Aflatoxin       0.00      0.00      0.00         4
                                   abnormal smell       0.00      0.00      0.00         1
                                  alcohol content       0.00      0.00      0.00         1
                                        allergens       0.00      0.00      0.00         1
                                           almond       0.65      0.68      0.67        22
                                        amygdalin       0.00      0.00      0.00         2
                           antibiotics, vet drugs       0.00      0.00      0.00         1
                                    bacillus spp.       0.00      0.00      0.00         4
                             bad smell / off odor       0.00      0.00      0.00         3
                                    bone fragment       0.00      0.00      0.00         5
                                bulging packaging       0.75      0.60      0.67         5
                                           cashew       0.00      0.00      0.00         8
                                          cereals       0.00      0.00      0.00         1
   cereals containing gluten and products thereof       0.54      0.52      0.53        48
                                         chemical       0.00      0.00      0.00         1
                 chemical compound (high content)       0.00      0.00      0.00         3
                 chemical compound (unauthorised)       0.00      0.00      0.00         4
                            clostridium botulinum       0.80      1.00      0.89         4
                                        coliforms       0.00      0.00      0.00         2
                          compositional deviation       0.00      0.00      0.00         2
                                  cronobacter spp       0.00      0.00      0.00         2
                 crustaceans and products thereof       0.00      0.00      0.00         5
                                damaged packaging       0.00      0.00      0.00         2
                                          dioxins       0.00      0.00      0.00         1
                      e 425 - konjac unauthorised       0.00      0.00      0.00         3
                        eggs and products thereof       0.76      0.66      0.70        38
                                    enteroviruses       0.00      0.00      0.00         1
                                 escherichia coli       0.77      0.70      0.73        47
                           false marketing claims       0.00      0.00      0.00         1
                        fish and products thereof       0.67      0.22      0.33         9
                                   foreign bodies       0.00      0.00      0.00         6
                                   glass fragment       0.39      0.64      0.48        11
                                        haloxyfop       0.00      0.00      0.00         1
                                         hazelnut       0.00      0.00      0.00         6
                                     heavy metals       0.30      0.60      0.40         5
                           high content of copper       0.00      0.00      0.00         1
                          high content of cyanide       0.00      0.00      0.00         4
                         high content of vitamins       0.00      0.00      0.00         0
                              improper conditions       0.00      0.00      0.00         2
                               improper packaging       0.00      0.00      0.00         1
                               incorrect labeling       0.00      0.00      0.00        11
                           incorrect use by dates       1.00      0.80      0.89         5
                                          insects       0.50      0.50      0.50         2
                                inspection issues       0.62      0.95      0.75        22
             insufficient labelling/documentation       0.00      0.00      0.00         2
                         labelling/misdescription       0.00      0.00      0.00         6
                           listeria monocytogenes       0.71      0.92      0.80       130
                                     listeria spp       0.00      0.00      0.00         2
                                   metal fragment       0.48      0.45      0.47        33
                    microbiological contamination       0.00      0.00      0.00         5
                        milk and products thereof       0.61      0.85      0.71       107
                                      misbranding       0.00      0.00      0.00         2
                                   misdescription       0.00      0.00      0.00         5
                                      mislabelled       0.00      0.00      0.00         2
                    molluscs and products thereof       0.00      0.00      0.00         1
                                           moulds       0.88      1.00      0.93         7
                     mustard and products thereof       0.75      0.86      0.80         7
                                         nitrogen       0.00      0.00      0.00         1
                        non compliance with HACCP       0.00      0.00      0.00         1
                                        norovirus       1.00      1.00      1.00         1
                                             nuts       0.00      0.00      0.00         6
                                       ochratoxin       0.00      0.00      0.00         1
                                            other       0.18      0.50      0.27        22
                             other not classified       0.20      0.14      0.17         7
            other not classified allergen hazards       0.00      0.00      0.00         1
          other not classified biological hazards       0.00      0.00      0.00         2
            other not classified chemical hazards       0.00      0.00      0.00         6
  other not classified hazards for foreign bodies       0.00      0.00      0.00         2
                                 packaging defect       0.00      0.00      0.00         5
                                             pahs       0.00      0.00      0.00         1
       paralytic shellfish poisoning (psp) toxins       0.00      0.00      0.00         1
                              pathogenic bacteria       0.00      0.00      0.00         1
                                          patulin       0.00      0.00      0.00         1
                     peanuts and products thereof       0.53      0.62      0.57        42
                                        pecan nut       0.00      0.00      0.00         1
                                   phenylpyrazole       0.00      0.00      0.00         1
                                    pistachio nut       0.00      0.00      0.00         1
                                 plastic fragment       0.45      0.79      0.57        39
                 polycyclic aromatic hydrocarbons       0.00      0.00      0.00         1
                              poor hygienic state       0.00      0.00      0.00         1
                    poor or insufficient controls       0.00      0.00      0.00         1
                                       processing       0.50      0.60      0.55        10
                 product category/characteristics       0.00      0.00      0.00         3
                                 pseudomonas spp.       0.00      0.00      0.00         1
                                 rubber fragments       0.00      0.00      0.00         7
                                       salmonella       0.80      0.85      0.82       133
                sesame seeds and products thereof       1.00      0.40      0.57         5
                    soybeans and products thereof       0.36      0.59      0.45        29
                    specified risk material (srm)       0.00      0.00      0.00         1
                                         spoilage       1.00      0.20      0.33         5
                                   staphylococcus       0.00      0.00      0.00         1
                              sulphates/sulphites       0.00      0.00      0.00         1
                                  sulphur dioxide       0.00      0.00      0.00         2
                    sulphur dioxide and sulphites       0.50      0.71      0.59        17
                                taste disturbance       0.00      0.00      0.00         1
too high content of fluorinated organic chemicals       0.00      0.00      0.00         1
                                            toxin       0.00      0.00      0.00         6
                      unauthorised colour sudan 4       0.00      0.00      0.00         1
                              unauthorised import       0.00      0.00      0.00         2
                            unauthorised operator       0.00      0.00      0.00         3
            unauthorised substance ethylene oxide       1.00      1.00      1.00         8
                unauthorised substance sildenafil       0.50      1.00      0.67         1
                              undeclared additive       0.00      0.00      0.00         1
                           undeclared constituent       0.00      0.00      0.00         1
                      unfit for human consumption       0.00      0.00      0.00         2
                                       vibrio spp       0.00      0.00      0.00         2
                                            virus       0.00      0.00      0.00         2
                                           walnut       0.80      0.50      0.62         8

                                         accuracy                           0.60      1017
                                        macro avg       0.19      0.19      0.18      1017
                                     weighted avg       0.52      0.60      0.55      1017

In [20]:
model_hazard.save_pretrained("bert_hazard")
np.save("bert_hazard/label_encoder.npy", le_hazard.classes_)

### Label: `Product`

In [21]:
label = 'product'

# Create DataLoader objects
train_dataloader, dev_dataloader, le_product = prepare_data(label)

Map:   0%|          | 0/4065 [00:00<?, ? examples/s]

Map:   0%|          | 0/1017 [00:00<?, ? examples/s]

In [22]:
model_product = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(data[label].unique()))
model_product.to('cuda')  # Move model to GPU if available

optimizer = AdamW(model_product.parameters(), lr=5e-5)
num_epochs = 3
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    name="linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)
model_product.train()
progress_bar = tqdm(range(num_training_steps))
for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_product(**batch)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

  0%|          | 0/1527 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2888: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [23]:
model_product.eval()
total_predictions = []
with torch.no_grad():
    for batch in dev_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_product(**batch)
        predictions = torch.argmax(outputs.logits, dim=-1)
        total_predictions.extend([p.item() for p in predictions])

predicted_labels = le_product.inverse_transform(total_predictions)
gold_labels = le_product.inverse_transform(dev_df.label.values)
print(classification_report(gold_labels, predicted_labels, zero_division=0))

dev_df['predictions-product'] = predicted_labels

                                                                        precision    recall  f1-score   support

                                                Catfishes (freshwater)       0.00      0.00      0.00         2
                                                 Fishes not identified       0.21      0.80      0.33         5
                                                    Groupers (generic)       0.00      0.00      0.00         1
                                              Not classified pork meat       0.00      0.00      0.00         1
                                            Pangas catfishes (generic)       0.00      0.00      0.00         1
                                   Precooked cooked pork meat products       0.00      0.00      0.00         3
                                    Torpedo-shaped catfishes (generic)       0.00      0.00      0.00         1
                                                       adobo seasoning       0.00      0.00      0.00         1
                                                   alcoholic beverages       0.00      0.00      0.00         2
                                                       alfalfa sprouts       0.00      0.00      0.00         3
                                                                 algae       0.00      0.00      0.00         1
                                                 all purpose seasoning       0.00      0.00      0.00         1
                                                              allspice       0.00      0.00      0.00         1
                                                           almond milk       0.00      0.00      0.00         1
                                                         almond powder       0.00      0.00      0.00         1
                                                       almond products       0.00      0.00      0.00         1
                                                               almonds       0.00      0.00      0.00         3
                                                            appetizers       0.00      0.00      0.00         1
                                                           apple juice       0.00      0.00      0.00         3
                                                       apricot kernels       0.00      0.00      0.00         2
                                                              apricots       0.00      0.00      0.00         1
                                                             baby food       0.00      0.00      0.00         3
                                                          baby spinach       0.00      0.00      0.00         3
                                                       bakery products       0.00      0.00      0.00         2
                                                                  bars       0.00      0.00      0.00         4
                                                                 basil       0.00      0.00      0.00         1
                                                     basil pesto sauce       0.00      0.00      0.00         2
                                                            batter mix       0.00      0.00      0.00         1
                                                            bean paste       0.00      0.00      0.00         1
                                                            bean sauce       0.00      0.00      0.00         2
                                                                 beans       0.00      0.00      0.00         1
                                                                  beef       0.00      0.00      0.00         2
                                                             beef meat       0.00      0.00      0.00         1
                                                         beef products       0.00      0.00      0.00         7
                                                           beef tallow       0.00      0.00      0.00         1
                                                           beef tongue       0.00      0.00      0.00         1
                                                                  beer       0.37      1.00      0.54         7
                                                              beverage       0.00      0.00      0.00         1
                                                              biscuits       0.40      0.33      0.36         6
                                                bitter apricot kernels       0.00      0.00      0.00         3
                                                          black pepper       0.00      0.00      0.00         1
                                                           blue cheese       0.00      0.00      0.00         1
                                                       bolognese sauce       0.00      0.00      0.00         1
                                                         bottled water       0.00      0.00      0.00         3
                                                 bovine meat and offal       0.00      0.00      0.00         1
                                                           brazil nuts       0.00      0.00      0.00         1
                                                                 bread       0.46      0.86      0.60         7
                                           bread and products therefor       0.00      0.00      0.00         2
                                                           bread crumb       0.00      0.00      0.00         1
                                                     breakfast cereals       0.00      0.00      0.00         2
                                                           brie cheese       0.00      0.00      0.00         3
                                                               brioche       0.00      0.00      0.00         1
                                                              broccoli       0.00      0.00      0.00         3
                                                          broccoli mix       0.00      0.00      0.00         1
                                                                broths       0.00      0.00      0.00         1
                                                           brown beans       0.00      0.00      0.00         1
                                                              brownies       0.00      0.00      0.00         1
                                                                  buns       0.00      0.00      0.00         2
                                                               burrata       0.00      0.00      0.00         1
                                                burrito (ready to eat)       0.00      0.00      0.00         1
                                                                 cakes       0.26      0.75      0.39        16
                                                               candies       0.00      0.00      0.00         4
                                                    canned black beans       0.00      0.00      0.00         1
                                                           canned corn       0.00      0.00      0.00         1
                                                  canned fish products       0.00      0.00      0.00         1
                                                    cantaloupe (fresh)       0.00      0.00      0.00         1
                                                   carbonated beverage       0.00      0.00      0.00         1
                                                                cashew       0.00      0.00      0.00         3
                                                           cauliflower       0.00      0.00      0.00         1
                                                           cereal bars       0.00      0.00      0.00         2
                                                        cheddar cheese       0.00      0.00      0.00         3
                                                                cheese       0.31      0.79      0.44        19
                                                       cheese products       0.00      0.00      0.00         2
                                                         cheese spread       0.00      0.00      0.00         3
                                                            chia seeds       0.00      0.00      0.00         2
                                                               chicken       0.00      0.00      0.00         5
                                                chicken based products       0.23      0.88      0.36        25
                                                        chicken breast       0.00      0.00      0.00         8
                                                 chicken meat products       0.00      0.00      0.00         1
                                                   chicken noodle soup       0.00      0.00      0.00         2
                                                  chicken preparations       0.00      0.00      0.00         6
                                                        chicken slices       0.00      0.00      0.00         1
                                            chilled boneless pork meat       0.00      0.00      0.00         1
                                                       chilled chicken       0.00      0.00      0.00         1
                                                 chilled pork sausages       0.00      0.00      0.00         1
                                                        chilled salads       0.00      0.00      0.00         2
                                                          chilli sauce       0.00      0.00      0.00         1
                                                             chocolate       0.00      0.00      0.00         5
                                                        chocolate bars       0.12      0.12      0.12         8
                                                     chocolate dessert       0.00      0.00      0.00         1
                                                        chocolate eggs       0.00      0.00      0.00         2
                                         chocolate flavoured meringues       0.00      0.00      0.00         1
                                                    chocolate products       0.00      0.00      0.00         5
                                                            chocolates       0.00      0.00      0.00         1
                                                               chorizo       0.00      0.00      0.00         2
                                                                 cider       1.00      1.00      1.00         2
                                                                 clams       0.00      0.00      0.00         1
                                                        clams (canned)       0.00      0.00      0.00         1
                                                cocktail sausage rolls       0.00      0.00      0.00         1
                                                         coconut drink       0.00      0.00      0.00         1
                                                         coconut juice       0.00      0.00      0.00         2
                                                          coconut milk       0.00      0.00      0.00         2
                                                    coconut milk drink       0.00      0.00      0.00         1
                                                              coconuts       0.29      1.00      0.44         4
                                                                   cod       0.00      0.00      0.00         1
                                                          coffee beans       0.00      0.00      0.00         3
                                                          coffee drink       0.00      0.00      0.00         1
                                                               colours       0.00      0.00      0.00         1
                                                         confectionery       0.00      0.00      0.00         2
                                                        cooked chicken       0.00      0.00      0.00         4
                                                            cooked ham       0.00      0.00      0.00         1
                                                               cookies       0.56      0.78      0.65        18
                                                         cooking sauce       0.00      0.00      0.00         1
                                                                  corn       0.00      0.00      0.00         5
                                                            courgettes       0.00      0.00      0.00         1
                                                       cow milk cheese       0.00      0.00      0.00         2
                                                              crackers       0.00      0.00      0.00         0
                                                         cranberry jam       0.00      0.00      0.00         1
                                                          cream cheese       0.00      0.00      0.00         1
                                                                crisps       0.00      0.00      0.00         2
                                                          cumin powder       0.00      0.00      0.00         1
                                                              cupcakes       0.00      0.00      0.00         3
                                                           curd cheese       0.00      0.00      0.00         1
                                                       cured pork meat       0.00      0.00      0.00         1
                                                                 curry       0.04      1.00      0.07         1
                                                          curry sauces       0.00      0.00      0.00         1
                                                               custard       0.00      0.00      0.00         1
                                         dark chocolate coated almonds       0.00      0.00      0.00         2
                                                       dark chocolates       0.09      0.80      0.16         5
                                                              desserts       0.00      0.00      0.00         5
                                                    dietary supplement       0.00      0.00      0.00         4
                                                             dip-sauce       0.00      0.00      0.00         2
                                                                donuts       0.00      0.00      0.00         1
                                                              dressing       0.00      0.00      0.00         1
                                                       dressing sauces       0.00      0.00      0.00         2
                                                        dried apricots       0.33      0.50      0.40         2
                                                           dried beans       0.00      0.00      0.00         0
                                                       dried beef meat       0.00      0.00      0.00         5
                                                         dried coconut       0.00      0.00      0.00         1
                                                     dried cranberries       0.00      0.00      0.00         2
                                                            dried figs       0.00      0.00      0.00         2
                                                       dried fruit mix       0.00      0.00      0.00         1
                                                       dried mushrooms       0.00      0.00      0.00         1
                                                           dried plums       0.00      0.00      0.00         3
                                                          drink powder       0.00      0.00      0.00         1
                                             drinking chocolate powder       0.00      0.00      0.00         1
                                                                  duck       0.00      0.00      0.00         1
                                                             dumplings       0.00      0.00      0.00         4
                                                             egg rolls       0.00      0.00      0.00         1
                                                                  eggs       0.80      0.80      0.80        10
               emulsifiers, stabilizers, thickeners and gelling agents       0.00      0.00      0.00         1
                                                           fajita meal       0.00      0.00      0.00         1
                                                          fennel seeds       0.00      0.00      0.00         1
                                                   fermented beef meat       0.00      0.00      0.00         2
                                                fermented milk product       0.00      0.00      0.00         1
                                                fish and fish products       0.00      0.00      0.00         1
                                                         fish products       0.00      0.00      0.00         2
                              flavoured fresh and creamy cheese spread       0.00      0.00      0.00         1
                                                  flavoured soft drink       0.00      0.00      0.00         1
                                   flavoured whey protein preparations       0.00      0.00      0.00         1
                                                              flaxseed       0.00      0.00      0.00         1
                                                                 flour       0.56      1.00      0.71         5
                                                       food supplement       0.00      0.00      0.00         2
                                                            fresh beef       0.00      0.00      0.00         1
                                                           fresh dough       0.00      0.00      0.00         1
                                                       fresh mushrooms       0.67      1.00      0.80         4
                                                         fresh parsley       0.00      0.00      0.00         1
                                                            fresh pork       0.00      0.00      0.00         1
                                  fresh poultry and poultry prepations       0.00      0.00      0.00         1
                                    fresh processed beef meat products       0.00      0.00      0.00         1
                                                      fresh vegetables       0.00      0.00      0.00         1
                                                   frozen beef patties       0.00      0.00      0.00         1
                                                 frozen beef trimmings       0.00      0.00      0.00         1
                                                    frozen berries mix       0.00      0.00      0.00         1
                                                  frozen boneless beef       0.00      0.00      0.00         2
                                                        frozen chicken       0.00      0.00      0.00         1
                                    frozen chicken strips with tendons       0.00      0.00      0.00         1

In [24]:
model_product.save_pretrained("bert_product")
np.save("bert_product/label_encoder.npy", le_product.classes_)
tokenizer.save_pretrained("bert_tokenizer")

('bert_tokenizer/tokenizer_config.json',
 'bert_tokenizer/special_tokens_map.json',
 'bert_tokenizer/vocab.txt',
 'bert_tokenizer/added_tokens.json')

In [25]:
!zip bert_baseline.zip bert_*

  adding: bert_hazard/ (stored 0%)
  adding: bert_hazard_category/ (stored 0%)
  adding: bert_product/ (stored 0%)
  adding: bert_product_category/ (stored 0%)
  adding: bert_tokenizer/ (stored 0%)

/usr/lib/python3.10/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()

## Evaluate Sub-Task

In [26]:
score = compute_score(
    dev_df['hazard'], dev_df['product'],
    dev_df['predictions-hazard'], dev_df['predictions-product']
)
print(f"Score Sub-Task 2: {score:.3f}")

Score Sub-Task 2: 0.119

# Predict test set:

Load test data from Codalab:

In [27]:
# load test data:
test_df = pd.read_csv('/kaggle/input/only-incidents-dataset/incidents.csv', index_col=0)

test_df.sample()

,year,month,day,country,title,text
799,2020,9,22,ie,Recall of a Batch of Coastguard Seafoods Smoke...,Recall of a Batch of Coastguard Seafoods Smoke...

Prediction function:

In [28]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification
from sklearn.preprocessing import LabelEncoder

def predict(texts, model_path, tokenizer_path="bert_tokenizer"):
    # Load the saved tokenizer
    tokenizer = BertTokenizer.from_pretrained(tokenizer_path)

    # Load the saved label encoder
    label_encoder = LabelEncoder()
    label_encoder.classes_ = np.load(model_path + '/label_encoder.npy', allow_pickle=True)

    # Load the saved model
    model = BertForSequenceClassification.from_pretrained(model_path)

    # Move model to GPU if available
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    # Tokenize the input texts
    inputs = tokenizer(texts, padding=True, truncation=True, return_tensors="pt")

    # Move inputs to the same device as the model
    inputs = {key: value.to(device) for key, value in inputs.items()}

    # Set the model to evaluation mode
    model.eval()

    # Make predictions
    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
        predictions = torch.argmax(logits, dim=-1)

    # Decode predictions back to string labels
    return label_encoder.inverse_transform(predictions.cpu().numpy().tolist())

Predict test data:

In [29]:
predictions = pd.DataFrame()

for column in ['hazard-category', 'product-category', 'hazard', 'product']:
  predictions[column] = predict(test_df.title.to_list(), f"bert_{column.replace('-', '_')}")

predictions.sample()

,hazard-category,product-category,hazard,product
381,packaging defect,alcoholic beverages,sulphur dioxide and sulphites,ice cream

Save predictions:

In [30]:
import os
from shutil import make_archive

# save predictions to a new folder:
os.makedirs('./submission/', exist_ok=True)
predictions.to_csv('./submission/submission.csv')

# zip folder
make_archive('./submission', 'zip', './submission')

'/kaggle/working/submission.zip'

### For the VALIDATION DATASET

In [31]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from transformers import BertTokenizer, BertForSequenceClassification, AdamW, get_scheduler, DataCollatorWithPadding # Import BertForSequenceClassification


# load training data:
data = pd.read_csv('/kaggle/input/incidents-validation-dataset/incidents_valid.csv', index_col=0)
train_df, dev_df = train_test_split(data, test_size=0.2, random_state=2024)

train_df.sample()

,year,month,day,country,title,text,hazard-category,product-category,hazard,product
7,2000,8,23,au,Brown Brothers—1999 Moscato Wine,PRA No. 2000/4412 Date published 23 Aug 2000 P...,packaging defect,alcoholic beverages,packaging defect,wine

In [32]:
data.title.str.split().apply(len).describe()

count    565.000000
mean      12.748673
std        5.281493
min        1.000000
25%       10.000000
50%       13.000000
75%       15.000000
max       46.000000
Name: title, dtype: float64

In [34]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification, AdamW, get_scheduler, DataCollatorWithPadding

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

def tokenize_function(examples):
    return tokenizer(examples['title'], padding=True, truncation=True)
from transformers import BertTokenizer, BertForSequenceClassification, AdamW, get_scheduler, DataCollatorWithPadding

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

def tokenize_function(examples):
    return tokenizer(examples['title'], padding=True, truncation=True)

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [35]:
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import DataLoader
from datasets import Dataset

def prepare_data(label):
    # encode labels:
    label_encoder = LabelEncoder()
    label_encoder.fit(data[label])

    train_df['label'] = label_encoder.transform(train_df[label])
    dev_df['label'] = label_encoder.transform(dev_df[label])

    # Convert DataFrame to Hugging Face Dataset
    train_dataset = Dataset.from_pandas(train_df)
    dev_dataset = Dataset.from_pandas(dev_df)

    # Apply the tokenizer to the dataset
    train_dataset = train_dataset.map(tokenize_function, batched=True)
    dev_dataset = dev_dataset.map(tokenize_function, batched=True)

    # Create DataCollator to handle padding
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer, padding=True, max_length=16)

    # Convert dataset to PyTorch format
    train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])
    dev_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])

    # Create DataLoader objects
    return (
        DataLoader(train_dataset, shuffle=True, batch_size=8, collate_fn=data_collator),
        DataLoader(dev_dataset, batch_size=8, collate_fn=data_collator),
        label_encoder
    )

In [36]:
from sklearn.metrics import f1_score

def compute_score(hazards_true, products_true, hazards_pred, products_pred):
  # compute f1 for hazards:
  f1_hazards = f1_score(
    hazards_true,
    hazards_pred,
    average='macro'
  )

  # compute f1 for products:
  f1_products = f1_score(
    products_true[hazards_pred == hazards_true],
    products_pred[hazards_pred == hazards_true],
    average='macro'
  )

  return (f1_hazards + f1_products) / 2.

In [37]:
label = 'hazard-category'

# Create DataLoader objects
train_dataloader, dev_dataloader, le_hazard_category = prepare_data(label)

Map:   0%|          | 0/452 [00:00<?, ? examples/s]

Map:   0%|          | 0/113 [00:00<?, ? examples/s]

In [38]:
model_hazard_category = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(data[label].unique()))
model_hazard_category.to('cuda')

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=9, bias=True)
)

In [39]:
from tqdm.auto import tqdm

optimizer = AdamW(model_hazard_category.parameters(), lr=5e-5)

num_epochs = 10
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    name="linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)

model_hazard_category.train()

progress_bar = tqdm(range(num_training_steps))

for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  
        outputs = model_hazard_category(**batch)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

  0%|          | 0/570 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2888: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [40]:
from sklearn.metrics import classification_report

model_hazard_category.eval()
total_predictions = []
with torch.no_grad():
    for batch in dev_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_hazard_category(**batch)
        predictions = torch.argmax(outputs.logits, dim=-1)
        total_predictions.extend([p.item() for p in predictions])

predicted_labels = le_hazard_category.inverse_transform(total_predictions)
gold_labels = le_hazard_category.inverse_transform(dev_df.label.values)
print(classification_report(gold_labels, predicted_labels, zero_division=0))

dev_df['predictions-hazard-category'] = predicted_labels

                                precision    recall  f1-score   support

                     allergens       0.66      0.97      0.78        32
                    biological       0.90      0.86      0.88        44
                      chemical       1.00      0.60      0.75         5
food additives and flavourings       0.00      0.00      0.00         1
                foreign bodies       0.82      0.69      0.75        13
                         fraud       0.67      0.40      0.50        10
          organoleptic aspects       1.00      0.67      0.80         3
                  other hazard       0.00      0.00      0.00         1
              packaging defect       0.00      0.00      0.00         4

                      accuracy                           0.77       113
                     macro avg       0.56      0.47      0.50       113
                  weighted avg       0.76      0.77      0.75       113

In [41]:
print(predicted_labels)

['allergens' 'allergens' 'allergens' 'biological' 'allergens' 'allergens'
 'biological' 'fraud' 'biological' 'allergens' 'allergens' 'biological'
 'organoleptic aspects' 'biological' 'biological' 'allergens'
 'foreign bodies' 'foreign bodies' 'allergens' 'biological'
 'foreign bodies' 'allergens' 'allergens' 'allergens' 'foreign bodies'
 'biological' 'allergens' 'allergens' 'biological' 'allergens'
 'biological' 'allergens' 'biological' 'biological' 'biological'
 'other hazard' 'chemical' 'allergens' 'biological' 'allergens'
 'allergens' 'allergens' 'allergens' 'biological' 'biological'
 'foreign bodies' 'biological' 'allergens' 'allergens' 'biological'
 'biological' 'foreign bodies' 'allergens' 'organoleptic aspects'
 'biological' 'biological' 'biological' 'biological' 'foreign bodies'
 'allergens' 'allergens' 'biological' 'fraud' 'biological' 'biological'
 'biological' 'allergens' 'allergens' 'biological' 'allergens' 'allergens'
 'allergens' 'allergens' 'allergens' 'allergens' 'allergens' 'allergens'
 'biological' 'biological' 'allergens' 'allergens' 'fraud' 'biological'
 'foreign bodies' 'chemical' 'biological' 'allergens' 'foreign bodies'
 'biological' 'biological' 'other hazard' 'allergens' 'allergens'
 'allergens' 'chemical' 'foreign bodies' 'allergens' 'biological'
 'biological' 'fraud' 'allergens' 'allergens' 'biological' 'biological'
 'fraud' 'allergens' 'foreign bodies' 'biological' 'biological'
 'biological' 'biological' 'allergens' 'fraud']

In [42]:
model_hazard_category.save_pretrained("bert_hazard_category")
np.save("bert_hazard_category/label_encoder.npy", le_hazard_category.classes_)

In [43]:
label = 'product-category'

# Create DataLoader objects
train_dataloader, dev_dataloader, le_product_category = prepare_data(label)

Map:   0%|          | 0/452 [00:00<?, ? examples/s]

Map:   0%|          | 0/113 [00:00<?, ? examples/s]

In [45]:
model_product_category = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(data[label].unique()))
model_product_category.to('cuda') 

optimizer = AdamW(model_product_category.parameters(), lr=5e-5)
num_epochs = 10
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    name="linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)

model_product_category.train()
progress_bar = tqdm(range(num_training_steps))
for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}
        outputs = model_product_category(**batch)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

  0%|          | 0/570 [00:00<?, ?it/s]

In [46]:
model_product_category.eval()
total_predictions = []
with torch.no_grad():
    for batch in dev_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_product_category(**batch)
        predictions = torch.argmax(outputs.logits, dim=-1)
        total_predictions.extend([p.item() for p in predictions])

predicted_labels = le_product_category.inverse_transform(total_predictions)
gold_labels = le_product_category.inverse_transform(dev_df.label.values)
print(classification_report(gold_labels, predicted_labels, zero_division=0))

dev_df['predictions-product-category'] = predicted_labels

                                                   precision    recall  f1-score   support

                              alcoholic beverages       0.00      0.00      0.00         2
                      cereals and bakery products       0.50      0.55      0.52        11
     cocoa and cocoa preparations, coffee and tea       0.75      1.00      0.86         3
                                    confectionery       0.20      0.25      0.22         4
dietetic foods, food supplements, fortified foods       0.00      0.00      0.00         3
                                    fats and oils       0.00      0.00      0.00         1
                            fruits and vegetables       0.56      0.82      0.67        11
                                 herbs and spices       0.83      0.71      0.77         7
                                ices and desserts       1.00      0.67      0.80         3
                     meat, egg and dairy products       0.69      0.72      0.71        25
                          non-alcoholic beverages       0.50      1.00      0.67         3
                     nuts, nut products and seeds       1.00      0.71      0.83         7
                       other food product / mixed       0.00      0.00      0.00         2
                       prepared dishes and snacks       0.50      0.50      0.50        12
                                          seafood       1.00      0.60      0.75         5
             soups, broths, sauces and condiments       0.64      0.64      0.64        14

                                         accuracy                           0.62       113
                                        macro avg       0.51      0.51      0.50       113
                                     weighted avg       0.61      0.62      0.61       113

In [47]:
model_product_category.save_pretrained("bert_product_category")
np.save("bert_product_category/label_encoder.npy", le_product_category.classes_)

In [48]:
score = compute_score(
    dev_df['hazard-category'], dev_df['product-category'],
    dev_df['predictions-hazard-category'], dev_df['predictions-product-category']
)
print(f"Score Sub-Task 1: {score:.3f}")

Score Sub-Task 1: 0.534

In [49]:
label = 'hazard'

# Create DataLoader objects
train_dataloader, dev_dataloader, le_hazard = prepare_data(label)

Map:   0%|          | 0/452 [00:00<?, ? examples/s]

Map:   0%|          | 0/113 [00:00<?, ? examples/s]

In [50]:
model_hazard = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(data[label].unique()))
model_hazard.to('cuda')  # Move model to GPU if available

optimizer = AdamW(model_hazard.parameters(), lr=5e-5)

num_epochs = 3
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    name="linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)

model_hazard.train()

progress_bar = tqdm(range(num_training_steps))

for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_hazard(**batch)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

  0%|          | 0/171 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2888: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [51]:
model_hazard.eval()
total_predictions = []
with torch.no_grad():
    for batch in dev_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_hazard(**batch)
        predictions = torch.argmax(outputs.logits, dim=-1)
        total_predictions.extend([p.item() for p in predictions])

predicted_labels = le_hazard.inverse_transform(total_predictions)
gold_labels = le_hazard.inverse_transform(dev_df.label.values)
print(classification_report(gold_labels, predicted_labels, zero_division=0))

dev_df['predictions-hazard'] = predicted_labels

                                                precision    recall  f1-score   support

                                abnormal smell       0.00      0.00      0.00         1
                                     allergens       0.00      0.00      0.00         1
                                        almond       0.00      0.00      0.00         2
                             bulging packaging       0.00      0.00      0.00         2
cereals containing gluten and products thereof       0.00      0.00      0.00         2
                         clostridium botulinum       0.00      0.00      0.00         3
                                    cyclospora       0.00      0.00      0.00         1
                   e 425 - konjac unauthorised       0.00      0.00      0.00         1
                     eggs and products thereof       0.00      0.00      0.00         2
                                 enteroviruses       0.00      0.00      0.00         1
                              escherichia coli       0.43      0.50      0.46         6
                     fish and products thereof       0.00      0.00      0.00         1
                                foreign bodies       0.00      0.00      0.00         1
                                glass fragment       0.00      0.00      0.00         1
                                      hazelnut       0.00      0.00      0.00         1
                                  heavy metals       0.00      0.00      0.00         2
                            improper packaging       0.00      0.00      0.00         1
                        incorrect use by dates       0.00      0.00      0.00         1
                                       insects       0.00      0.00      0.00         1
                             inspection issues       0.00      0.00      0.00         2
          insufficient labelling/documentation       0.00      0.00      0.00         1
                      labelling/misdescription       0.00      0.00      0.00         2
                        listeria monocytogenes       0.44      0.73      0.55        15
                                metal fragment       0.00      0.00      0.00         3
                     milk and products thereof       0.19      1.00      0.32        12
                                   misbranding       0.00      0.00      0.00         1
                                misdescription       0.00      0.00      0.00         2
                                   mislabelled       0.00      0.00      0.00         1
                              packaging defect       0.00      0.00      0.00         1
                  peanuts and products thereof       0.00      0.00      0.00         1
                                 pistachio nut       0.00      0.00      0.00         1
                              plastic fragment       0.00      0.00      0.00         5
                                    processing       0.00      0.00      0.00         1
                              pseudomonas spp.       0.00      0.00      0.00         1
                              rubber fragments       0.00      0.00      0.00         2
                                    salmonella       0.67      0.71      0.69        17
                 soybeans and products thereof       0.00      0.00      0.00         7
                                      spoilage       0.00      0.00      0.00         2
                 sulphur dioxide and sulphites       0.00      0.00      0.00         2
                                         toxin       0.00      0.00      0.00         1
         unauthorised substance ethylene oxide       0.00      0.00      0.00         2

                                      accuracy                           0.34       113
                                     macro avg       0.04      0.07      0.05       113
                                  weighted avg       0.20      0.34      0.23       113

In [52]:
model_hazard.save_pretrained("bert_hazard")
np.save("bert_hazard/label_encoder.npy", le_hazard.classes_)

In [53]:
label = 'product'

# Create DataLoader objects
train_dataloader, dev_dataloader, le_product = prepare_data(label)

Map:   0%|          | 0/452 [00:00<?, ? examples/s]

Map:   0%|          | 0/113 [00:00<?, ? examples/s]

In [54]:
model_product = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(data[label].unique()))
model_product.to('cuda')  # Move model to GPU if available

optimizer = AdamW(model_product.parameters(), lr=5e-5)
num_epochs = 10
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    name="linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)
model_product.train()
progress_bar = tqdm(range(num_training_steps))
for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_product(**batch)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

  0%|          | 0/570 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2888: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [55]:
model_product.eval()
total_predictions = []
with torch.no_grad():
    for batch in dev_dataloader:
        batch = {k: v.to('cuda') for k, v in batch.items()}  # Move batch to GPU if available
        outputs = model_product(**batch)
        predictions = torch.argmax(outputs.logits, dim=-1)
        total_predictions.extend([p.item() for p in predictions])

predicted_labels = le_product.inverse_transform(total_predictions)
gold_labels = le_product.inverse_transform(dev_df.label.values)
print(classification_report(gold_labels, predicted_labels, zero_division=0))

dev_df['predictions-product'] = predicted_labels

                                        precision    recall  f1-score   support

                 Fishes not identified       0.00      0.00      0.00         1
                             baguettes       0.00      0.00      0.00         1
                            baking mix       0.00      0.00      0.00         1
           barbeque flavour corn snack       0.00      0.00      0.00         0
                                  bars       0.00      0.00      0.00         1
                     basil pesto sauce       0.00      0.00      0.00         1
                             bean curd       0.00      0.00      0.00         1
                                  beer       0.00      0.00      0.00         1
                              biscuits       0.00      0.00      0.00         0
                         bottled water       0.00      0.00      0.00         1
                                 bread       0.00      0.00      0.00         1
                             bread mix       0.00      0.00      0.00         1
                                bulgur       0.00      0.00      0.00         0
                                butter       0.00      0.00      0.00         1
                            butter oil       0.00      0.00      0.00         1
                                 cakes       0.50      0.50      0.50         2
                               candies       0.00      0.00      0.00         0
                   carbonated beverage       0.00      0.00      0.00         0
                           cereal bars       0.00      0.00      0.00         1
                        cheddar cheese       0.00      0.00      0.00         1
                                cheese       0.00      0.00      0.00         2
                          cheese sauce       0.00      0.00      0.00         1
                chicken based products       0.08      0.40      0.14         5
                        chicken breast       0.00      0.00      0.00         0
                  chicken preparations       0.00      0.00      0.00         2
                           chilled ham       0.00      0.00      0.00         1
               chocolate confectionery       0.00      0.00      0.00         1
                            chocolates       0.00      0.00      0.00         1
                               chorizo       0.00      0.00      0.00         1
                         coconut juice       0.00      0.00      0.00         1
                               cookies       0.00      0.00      0.00         2
                         cooking sauce       0.00      0.00      0.00         1
                                  corn       0.00      0.00      0.00         0
                          cream cheese       0.00      0.00      0.00         1
                                 curry       0.00      0.00      0.00         1
                       dark chocolates       0.00      0.00      0.00         2
                              desserts       0.00      0.00      0.00         1
                    dietary supplement       0.00      0.00      0.00         2
                             dip-sauce       0.00      0.00      0.00         1
                        dried apricots       0.00      0.00      0.00         1
                           dried plums       0.00      0.00      0.00         1
   flavoured whey protein preparations       0.00      0.00      0.00         1
                                 flour       0.00      0.00      0.00         0
                              focaccia       0.00      0.00      0.00         0
                       fresh mushrooms       0.00      0.00      0.00         1
                  frozen chicken wings       0.00      0.00      0.00         1
frozen pre-fried breaded fish portions       0.00      0.00      0.00         1
                         garlic powder       0.00      0.00      0.00         1
                           goat cheese       0.00      0.00      0.00         1
                        green cardamon       0.00      0.00      0.00         1
                           ground beef       1.00      0.50      0.67         2
                                 halva       0.00      0.00      0.00         1
                             ice cream       0.07      1.00      0.13         2
                                   jam       0.00      0.00      0.00         1
                               jellies       0.00      0.00      0.00         1
                               ketchup       0.00      0.00      0.00         1
                         korean kimchi       0.00      0.00      0.00         1
                                  lamb       0.00      0.00      0.00         0
                              mackerel       0.00      0.00      0.00         1
                 massala spice mixture       0.00      0.00      0.00         1
                            mayonnaise       0.00      0.00      0.00         1
                                  milk       0.00      0.00      0.00         1
                         mineral water       0.00      0.00      0.00         1
                      mixed vegetables       0.00      0.00      0.00         1
                     mung bean sprouts       0.00      0.00      0.00         1
                             mushrooms       0.00      0.00      0.00         1
                               nut mix       0.00      0.00      0.00         1
                          organic tofu       0.00      0.00      0.00         1
                          oyster sauce       0.00      0.00      0.00         1
                                 pasta       0.00      0.00      0.00         1
                           pasta sauce       0.00      0.00      0.00         0
                               peanuts       0.00      0.00      0.00         3
                             pepperoni       0.00      0.00      0.00         1
                        pistachio nuts       0.00      0.00      0.00         1
                                 poppy       0.00      0.00      0.00         1
                pork and beef sausages       0.00      0.00      0.00         1
                          pork sausage       0.00      0.00      0.00         1
                          potato salad       0.00      0.00      0.00         1
                         prepared dish       0.00      0.00      0.00         0
                                  pâté       0.00      0.00      0.00         1
                     quorn preparation       0.00      0.00      0.00         1
                               ravioli       0.00      0.00      0.00         3
             ready to eat - cook meals       0.00      0.00      0.00         2
                                salads       0.00      0.00      0.00         3
                                salami       0.00      0.00      0.00         1
                                salmon       0.17      0.50      0.25         2
                                  salt       0.00      0.00      0.00         1
                            sandwiches       0.00      0.00      0.00         3
                                 sauce       0.00      0.00      0.00         2
                             seasoning       0.00      0.00      0.00         2
                            seasonings       0.00      0.00      0.00         1
                                sesame       0.00      0.00      0.00         1
                                  soup       0.00      0.00      0.00         3
                             spice mix       0.00      0.00      0.00         0
                               spreads       0.00      0.00      0.00         1
                          spring rolls       0.00      0.00      0.00         1
                               sprouts       0.00      0.00      0.00         1
        turkey and turkey preparations       0.00      0.00      0.00         1
             turmeric powder (curcuma)       0.00      0.00      0.00         1
                                  wine       0.00      0.00      0.00         1

                              accuracy                           0.06       113
                             macro avg       0.02      0.03      0.02       113
                          weighted avg       0.03      0.06      0.03       113

In [56]:
model_product.save_pretrained("bert_product")
np.save("bert_product/label_encoder.npy", le_product.classes_)
tokenizer.save_pretrained("bert_tokenizer")

('bert_tokenizer/tokenizer_config.json',
 'bert_tokenizer/special_tokens_map.json',
 'bert_tokenizer/vocab.txt',
 'bert_tokenizer/added_tokens.json')

In [57]:
!zip bert_baseline.zip bert_*

updating: bert_hazard/ (stored 0%)
updating: bert_hazard_category/ (stored 0%)
updating: bert_product/ (stored 0%)
updating: bert_product_category/ (stored 0%)
updating: bert_tokenizer/ (stored 0%)

/usr/lib/python3.10/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()

In [58]:
score = compute_score(
    dev_df['hazard'], dev_df['product'],
    dev_df['predictions-hazard'], dev_df['predictions-product']
)
print(f"Score Sub-Task 2: {score:.3f}")

Score Sub-Task 2: 0.032

### for TEST DATASET

In [59]:
# load test data:
test_df = pd.read_csv('/kaggle/input/incidents-testing-final-dataset/incidents_testing_final.csv', index_col=0)

test_df.sample()

,year,month,day,country,title,text
347,2016,6,5,us,Solomon Snacks and Bakery Recalls Meat Pie Pro...,"WASHINGTON, June 4, 2016 – Solomon Snacks and ..."

In [60]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification
from sklearn.preprocessing import LabelEncoder

def predict(texts, model_path, tokenizer_path="bert_tokenizer"):
    # Load the saved tokenizer
    tokenizer = BertTokenizer.from_pretrained(tokenizer_path)

    # Load the saved label encoder
    label_encoder = LabelEncoder()
    label_encoder.classes_ = np.load(model_path + '/label_encoder.npy', allow_pickle=True)

    # Load the saved model
    model = BertForSequenceClassification.from_pretrained(model_path)

    # Move model to GPU if available
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    # Tokenize the input texts
    inputs = tokenizer(texts, padding=True, truncation=True, return_tensors="pt")

    # Move inputs to the same device as the model
    inputs = {key: value.to(device) for key, value in inputs.items()}

    # Set the model to evaluation mode
    model.eval()

    # Make predictions
    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
        predictions = torch.argmax(logits, dim=-1)

    # Decode predictions back to string labels
    return label_encoder.inverse_transform(predictions.cpu().numpy().tolist())

In [61]:
predictions = pd.DataFrame()

for column in ['hazard-category', 'product-category', 'hazard', 'product']:
  predictions[column] = predict(test_df.title.to_list(), f"bert_{column.replace('-', '_')}")

predictions.sample()

    hazard-category              product-category      hazard    product
167      biological  nuts, nut products and seeds  salmonella  ice cream

In [62]:
import os
from shutil import make_archive

# save predictions to a new folder:
os.makedirs('./submission/', exist_ok=True)
predictions.to_csv('./submission/submission.csv')

# zip folder
make_archive('./submission', 'zip', './submission')

'/kaggle/working/submission.zip'